---
name: ACR Purge Reusable

inputs:
  registry:
    required: true
    type: string
  repository-regex:
    required: true
    type: string
  tag-regex:
    required: true
    type: string
  images-to-keep-count:
    required: true
    type: string

run:
  using: composite
  steps:
    steps:
      - id: run-purge-cmd
        run: |
          PURGE_CMD="acr purge --filter '${{ github.event.inputs.repository-regex }}:${{ github.event.inputs.tag-regex }}' --untagged \
                    --keep ${{ github.event.inputs.images-to-keep-count  }} --dry-run"
          
          echo $PURGE_CMD
          az acr run --cmd "$PURGE_CMD" --registry ${{ github.event.inputs.registry }} /dev/null