---
name: ACR Purge Reusable
description: Composite action to clean ACR

inputs:
  registry:
    required: true
    type: string
  repository-regex:
    required: true
    type: string
  tag-regex:
    required: true
    type: string
  duration-to-keep:
    required: true
    type: string
  images-to-keep-count:
    required: true
    type: string
  delete-untagged:
    required: false
    type: boolean
    default: false
  dry-run:
    required: false
    type: boolean
    default: true

runs:
  using: composite
  steps:
    - id: run-purge-cmd
      shell: bash
      run: |
        PURGE_CMD="acr purge --filter '${{ inputs.repository-regex }}:${{ inputs.tag-regex }}' \
                  --keep ${{ inputs.images-to-keep-count  }} --ago ${{ inputs.duration-to-keep }}"
        
        if [ ${{ inputs.delete-untagged }} = true ]; then
          PURGE_CMD="$PURGE_CMD --untagged"
        fi
        
        if [ ${{ inputs.dry-run }} = true ]; then
          PURGE_CMD="$PURGE_CMD --dry-run"
        fi
        
        echo $PURGE_CMD
        az acr run --cmd "$PURGE_CMD" --registry ${{ inputs.registry }} /dev/null