---
name: ACR Purge Reusable

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      repository-regex:
        required: true
        type: string
      tag-regex:
        required: true
        type: string
      images-to-keep-count:
        required: true
        type: string

jobs:
  acr-purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge containers
        run: |
          PURGE_CMD="acr purge --filter '${{ inputs.repository-regex }}:${{ inputs.tag-regex }}' --untagged --keep ${{ inputs.images-to-keep-count  }} --dry-run"
          az acr run --cmd "$PURGE_CMD" --registry ${{ inputs.registry }}
