---
name: TEST ACR PURGE

on:
  push

permissions:
  id-token: write
  contents: read

jobs:
  acr-purge-test:
    runs-on: ubuntu-latest
    env:
      azure-client-id: "a1f14a14-7101-4aad-b7f2-9fd042ffcac3"
      azure-tenant-id: "823215e9-78b0-4c49-bee0-c95059cec31c"
      azure-subscription-id: "39fb1aa5-7523-407e-bd5c-beeba374ffcf"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Purge containers
        uses: ./.github/actions/acr-purge
        with:
          azure-client-id: ${{ env.azure-client-id }}
          azure-tenant-id: ${{ env.azure-tenant-id }}
          azure-subscription-id: ${{ env.azure-subscription-id }}
          registry: "testArtem1"
          repository-regex: "samples/nginx"
          tag-regex: "version.*"
          duration-to-keep: "1d"
          delete-untagged: true
          dry-run: true

