---
name: TEST ACR PURGE

on:
  push

permissions:
  id-token: write
  contents: read

jobs:
  acr-purge-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Log into azure container registry
#        uses: docker/login-action@v3
#        with:
#          registry: "testArtem1.azurecr.io"
#          username: "testArtem1"
#          password: "nwoQLGxhx7mggXPXzY+bYRRXomfV3veqIP0O3WfKNb+ACRCH+X/H"

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: "a1f14a14-7101-4aad-b7f2-9fd042ffcac3"
          tenant-id: "823215e9-78b0-4c49-bee0-c95059cec31c"
          subscription-id: "39fb1aa5-7523-407e-bd5c-beeba374ffcf"
          enable-AzPSSession: true

      - name: Check Login
        run: az group list

      - name: Purge containers
        uses: ./.github/actions/acr-purge
        with:
          registry: "testArtem1"
          repository-regex: "samples/nginx"
          tag-regex: "version.*"
          duration-to-keep: "5h"
          images-to-keep-count: "2"

