---
name: TEST ACR PURGE

on:
  push

jobs:
  acr-purge-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log into azure container registry
        uses: docker/login-action@v2
        with:
          registry: "testArtem1.azurecr.io"
          username: "testArtem1"
          password: "nwoQLGxhx7mggXPXzY+bYRRXomfV3veqIP0O3WfKNb+ACRCH+X/H"

      - name: Purge containers
        uses: ./.github/actions/acr-purge
        with:
          registry: "testArtem1"
          repository-regex: "samples/nginx"
          tag-regex: "version.*"
          images_to-keep-count: "2"

