---
name: TEST ACR PURGE

on:
  push

jobs:
  acr-purge-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say hello
        run: | 
          echo "Hello world!"

      - name: Purge containers
        uses: ./../actions/acr-purge
        with:
          registry: "testArtem1"
          repository-regex: "samples/nginx"
          tag-regex: "version.*"
          images_to-keep-count: "2"

