name: TEST ACR PURGE
on:
  workflow_dispatch:
  schedule:
    - cron: '0 06,18 * * *'

jobs:
  acr-purge:
    uses: artemNaumenko/acr-build-helloworld-node/.github/workflows/acr-purge.yml@master
    with:
      registry: 'testArtem1'
      repository-regex: 'samples/nginx'
      tag-regex: 'version.*'
      images-to-keep-count: '2'
