---
name: TEST ACR PURGE

on:
  push

jobs:
  acr-purge-test:
    runs-on: ubuntu-latest
    steps:
      - name: Purge containers
        uses: .github/actions/acr-purge.yml
        with:
          registry: "testArtem1"
          repository-regex: "samples/nginx"
          tag-regex: "version.*"
          images-to-keep-count: "2"
