name: ACR Purge TEST
on: push

jobs:
  acr-purge:
    runs-on: ubuntu-latest
    env:
      registry: 'testArtem1' # Case insensitive ACR registry name
      regex-feature: "version*"
      days-to-keep-feature: "0"
      keep-master: "50"
      keep-feature: "2"
      username: "testArtem1"
      tenant: "823215e9-78b0-4c49-bee0-c95059cec31c"
      password: "nwoQLGxhx7mggXPXzY+bYRRXomfV3veqIP0O3WfKNb+ACRCH+X/H"
      service-principal-tenant: ${{ secrets.SP_TENANT }}
    steps:
      - name: Purge Feature Containers
        uses: Plabick/ACR-Container-Purge-Action@master
        with:
          registry: ${{ env.registry }}
          username: ${{ env.username }}
          tenant: ${{ env.tenant }}
          password: ${{ env.password }}
          tag-regex: ${{ env.regex-feature }}
          days-to-keep: ${{ env.days-to-keep-feature }}
          keep: ${{ env.keep-feature }}
          delete-untagged: True
