name: ACR Purge
on:
  workflow_dispatch:
  schedule:
    - cron: '0 06,18 * * *'
jobs:
  acr-purge:
    runs-on: ubuntu-20.04
    env:
      registry: 'testArtem1'
      regex-feature: "version*"
      days-to-keep-feature: "0"
      keep-feature: "2"
      service-principal-username: "testArtem1"
      service-principal-tenant: "823215e9-78b0-4c49-bee0-c95059cec31c"
      password: "nwoQLGxhx7mggXPXzY+bYRRXomfV3veqIP0O3WfKNb+ACRCH+X/H"
    steps:
      - name: Purge Feature Containers
        uses: Plabick/ACR-Container-Purge-Action@master
        with:
          registry: ${{ env.registry }}
          username: ${{ env.service-principal-username }}
          tenant: ${{ env.service-principal-tenant }}
          password: ${{ env.password }}
          tag-regex: ${{ env.regex-feature }}
          days-to-keep: ${{ env.days-to-keep-feature }}
          keep: ${{ env.keep-feature }}
          delete-untagged: True
